version: '3.0'

expectations:
  population_size: 10000

actions:

  generate_cohort_stppop_map:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_1_stppop_map --output-dir=output/cohorts
    outputs:
      highly_sensitive:
        cohort: output/cohorts/input_1_stppop_map.csv

  plot_stppop_map:
    run: r:latest analysis/1-plot-stppop_map.R
    needs: [generate_cohort_stppop_map]
    outputs:
      moderately_sensitive:
        figure1: output/plots/plot_stppop_bar_names.png
        figure2: output/plots/plot_stppop_map.png
