version: '3.0'

expectations:
  population_size: 10000

actions:

  generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-dir=output/cohorts --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/cohorts/input.csv.gz

  counts:
    run: r:latest analysis/counts.r
    needs: [generate_cohort]
    outputs:
      moderately_sensitive:
        death_count: output/tables/death_count.csv
        imd_table: output/tables/imd_count.csv
        age_sex_table: output/tables/age_sex_count.csv
        age_table: output/tables/age_count.csv


  plots:
    run: r:latest analysis/plots.R
    needs: [counts]
    outputs:
      moderately_sensitive:
        figure1: output/plots/Cause_of_Death_count.svg
        figure2: output/plots/imd_count.svg
        figure3: output/plots/age_sex_count.svg
        figure4: output/plots/age_count.svg
        figure5: output/plots/sex_count.svg


  calculate_tpp_coverage:
    run: r:latest analysis/calculate_tpp_coverage.R
    needs: [generate_cohort]
    outputs:
      moderately_sensitive:
        msoa_table: output/tables/tpp_pop_all.csv.gz
        msoa_map: output/plots/tpp_coverage_map.svg
        


