version: '3.0'

expectations:
  population_size: 10000

actions:

  generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-dir=output/cohorts --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/cohorts/input.csv.gz

  counts:
    run: r:latest analysis/counts.r
    needs: [generate_cohort]
    outputs:
      moderately_sensitive:
        death_count: output/tables/death_count.csv
        imd_table: output/tables/imd_count.csv
        age_sex_table: output/tables/age_sex_count.csv
        age_table: output/tables/age_count.csv
        ethnicity_table: output/tables/ethnic_group.csv


  plots:
    run: r:latest analysis/plots.R
    needs: [counts]
    outputs:
      moderately_sensitive:
        figure1: output/plots/Cause_of_Death_count.jpg
        figure2: output/plots/imd_count.jpg
        figure3: output/plots/age_sex_count.jpg
        figure4: output/plots/age_count.jpg
        figure5: output/plots/sex_count.jpg
        figure6: output/plots/Cause_of_Death_count_eng.jpg
        figure7: output/plots/age_sex_count_eng.jpg
        figure8: output/plots/age_count_eng.jpg
        figure9: output/plots/sex_count_eng.jpg
        figure10: output/plots/ethnicity_count_eng.jpg
        figure11: output/plots/ethnicity_count.jpg
        figure12: output/plots/ethnicity16_count_eng.jpg
        figure13: output/plots/ethnicity16_count.jpg

  calculate_tpp_coverage:
    run: r:latest analysis/calculate_tpp_coverage.R
    needs: [generate_cohort]
    outputs:
      moderately_sensitive:
        region_table: output/tables/tpp_pop_all.csv
        region_map: output/plots/tpp_coverage_map.jpg
